- hosts: win_app
  tasks:
  - name: Resize
    win_shell: echo rescan | diskpart
  - name: Resize
    win_shell: "Resize-Partition -DriveLetter C -Size $(Get-PartitionSupportedSize -DriveLetter C).SizeMax"
