- hosts: all
  tasks:

-name: Test Drive
  win_shell: cd "C:\Users\aspnurali\Desktop"
  
- name: Partition Size
    win_shell: "$size = (Get-PartitionSupportedSize -DriveLetter H)"
    
- name: Resize
    win_shell: "Resize-Partition -DriveLetter H -Size $size.SizeMax"
