- hosts: all
  tasks:

- name: Partition Size
    win_shell: "$size = (Get-PartitionSupportedSize -DriveLetter H)"
    
- name: Resize
    win_shell: "Resize-Partition -DriveLetter H -Size $size.SizeMax"
